{{- if .Values.azureKeyVault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "enterprise.fullname" . }}-spc
  labels:
    {{- include "enterprise.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "enterprise.fullname" . }}-mongodb-secret
      type: Opaque
      data:
        - key: MONGODB_URI
          objectName: {{ .Values.azureKeyVault.secretName }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: {{ .Values.azureKeyVault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.azureKeyVault.keyVaultName | quote }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: {{ .Values.azureKeyVault.secretName | quote }}
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
{{- end }}
