# Default Helm values for Enterprise Services
nameOverride: ""
fullnameOverride: ""

replicaCount: 3

image:
  repository: acrsaasprod.azurecr.io/service
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

serviceAccount:
  create: true
  annotations:
    azure.workload.identity/client-id: ""
  name: ""

azureKeyVault:
  enabled: true
  userAssignedIdentityID: "9133ffb3-4316-4116-ac82-d40c4d073594"
  keyVaultName: "kvsaasprod9rmf1t"
  tenantId: "bec1eb95-e192-4068-a6e5-4847ec729d6f"
  secretName: "mongodb-uri-service"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 20000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
  host: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

kedaAutoscaling:
  enabled: false
  cooldownPeriod: 300
  pollingInterval: 30
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers: []

env:
  NODE_ENV: "production"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo-distributor.monitoring.svc.cluster.local:4317"

runtimeSecretName: "connectsphere-runtime-secrets"

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
